# action.yml
name: 'Build'
description: 'Build our sphinx documentation package'
inputs:
  make-target:  # what to make
    description: 'Sphinx Make Target'
    required: true
    default: 'html'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.make-target }}